CREATE TABLE tlsample.stg_edi_his_ins (
  ins_id NUMBER(*,0) NOT NULL,
  ben_id NUMBER(*,0) NOT NULL,
  his_id NUMBER(*,0) NOT NULL,
  carrier_code CHAR(4 BYTE),
  policy_nbr CHAR(30 BYTE),
  segment_type CHAR,
  scope_of_coverage CHAR(16 BYTE),
  policy_ymdeff CHAR(8 BYTE),
  policy_ymdend CHAR(8 BYTE),
  ymd_last_change CHAR(8 BYTE),
  last_change_source CHAR(4 BYTE),
  trans_type CHAR,
  operator_id CHAR(3 BYTE),
  absent_parent_ins_flag CHAR,
  ins_status_code CHAR,
  relationship_code CHAR,
  dependent_cov_avail CHAR,
  iex_source_cov CHAR,
  termination_reason CHAR(2 BYTE),
  followup_file_flag CHAR,
  policy_holder_ssn CHAR(9 BYTE),
  ph_last_name CHAR(15 BYTE),
  ph_first_name CHAR(10 BYTE),
  ph_mi CHAR,
  ph_addr1 CHAR(26 BYTE),
  ph_addr2 CHAR(26 BYTE),
  ph_city CHAR(18 BYTE),
  ph_state CHAR(2 BYTE),
  ph_zip CHAR(9 BYTE),
  ph_phone_nbr CHAR(10 BYTE),
  ge_name CHAR(30 BYTE),
  ge_number CHAR(20 BYTE),
  ge_addr1 CHAR(26 BYTE),
  ge_addr2 CHAR(26 BYTE),
  ge_city CHAR(18 BYTE),
  ge_state CHAR(2 BYTE),
  ge_zip CHAR(9 BYTE),
  ge_phone_nbr CHAR(10 BYTE),
  union_name CHAR(30 BYTE),
  union_local_nbr CHAR(20 BYTE)
);